import { describe, it, expect, vi } from 'vitest'
import { SqlcExtractor } from '../sqlc'
import type { ExtractorContext } from '../../../base'

function makeExtractor(files: Record<string, string>): SqlcExtractor {
  const ctx: ExtractorContext = {
    sourceDir: '/repo',
    approach: { language: 'Go', approach: 'sqlc', confidence: 'high', signals: [] },
    repoFullName: 'test/repo',
  }
  const extractor = new SqlcExtractor(ctx)
  vi.spyOn(extractor as any, 'glob').mockImplementation(async (pattern: string) => {
    return Object.keys(files).filter((f) => {
      if (pattern.includes('*.sql.go')) return f.endsWith('.sql.go')
      if (pattern.includes('*.sql')) return f.endsWith('.sql') && !f.endsWith('.sql.go')
      return false
    })
  })
  vi.spyOn(extractor as any, 'readFile').mockImplementation(async (path: string) => {
    if (files[path] === undefined) throw new Error(`File not found: ${path}`)
    return files[path]
  })
  return extractor
}

describe('SqlcExtractor', () => {
  describe('generated Go file (*.sql.go)', () => {
    it('extracts result structs from generated sqlc Go code', async () => {
      const extractor = makeExtractor({
        'db/queries.sql.go': `
// Code generated by sqlc. DO NOT EDIT.
package db

import "time"

type GetUserRow struct {
    ID        int64     \`db:"id" json:"id"\`
    Email     string    \`db:"email" json:"email"\`
    Name      string    \`db:"name" json:"name"\`
    CreatedAt time.Time \`db:"created_at" json:"created_at"\`
}

type ListUsersRow struct {
    ID    int64  \`db:"id" json:"id"\`
    Email string \`db:"email" json:"email"\`
}

type CreateUserParams struct {
    Email string \`db:"email" json:"email"\`
    Name  string \`db:"name" json:"name"\`
}
`,
      })

      const result = await extractor.extract()
      expect(result.entities.length).toBeGreaterThanOrEqual(3)

      const getUserRow = result.entities.find((e) => e.name === 'GetUserRow')
      expect(getUserRow).toBeDefined()
      expect(getUserRow?.entityType).toBe('query_result')

      const idField = getUserRow?.fields.find((f) => f.name === 'ID')
      expect(idField?.type).toBe('integer')
      expect(idField?.columnName).toBe('id')

      const emailField = getUserRow?.fields.find((f) => f.name === 'Email')
      expect(emailField?.type).toBe('string')
    })
  })

  describe('raw SQL query file', () => {
    it('extracts named queries from .sql files with sqlc annotations', async () => {
      const extractor = makeExtractor({
        'queries/user.sql': `
-- name: GetUser :one
SELECT id, email, name, created_at
FROM users
WHERE id = $1;

-- name: ListUsers :many
SELECT id, email, name
FROM users
ORDER BY created_at DESC;

-- name: CreateUser :one
INSERT INTO users (email, name)
VALUES ($1, $2)
RETURNING *;

-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1;
`,
      })

      const result = await extractor.extract()
      expect(result.entities.length).toBeGreaterThanOrEqual(4)

      const getUser = result.entities.find((e) => e.name === 'GetUser')
      expect(getUser).toBeDefined()
      expect(getUser?.entityType).toBe('named_query')
      expect(getUser?.metadata?.queryType).toBe('one')

      const listUsers = result.entities.find((e) => e.name === 'ListUsers')
      expect(listUsers?.metadata?.queryType).toBe('many')

      const deleteUser = result.entities.find((e) => e.name === 'DeleteUser')
      expect(deleteUser?.metadata?.queryType).toBe('exec')
    })

    it('extracts SELECT column names from simple queries', async () => {
      const extractor = makeExtractor({
        'queries/user.sql': `
-- name: GetUser :one
SELECT id, email, name
FROM users
WHERE id = $1;
`,
      })

      const result = await extractor.extract()
      const query = result.entities[0]
      const fieldNames = query.fields.map((f) => f.name)
      expect(fieldNames).toContain('id')
      expect(fieldNames).toContain('email')
      expect(fieldNames).toContain('name')
    })
  })

  describe('stats', () => {
    it('reports correct stats', async () => {
      const extractor = makeExtractor({
        'db/queries.sql.go': `
type GetUserRow struct {
    ID    int64  \`db:"id"\`
    Email string \`db:"email"\`
}
`,
      })

      const result = await extractor.extract()
      expect(result.stats.filesScanned).toBe(1)
      expect(result.stats.entitiesFound).toBeGreaterThanOrEqual(1)
    })
  })
})
